CXX := clang++
NVCC := nvcc -ccbin "D:\Program Files\VisualStudio\VC\Tools\MSVC\14.51.36231\bin\Hostx64\x64"

INCLUDES := \
	-I./include \
	-I./libs

CXXFLAGS := -g $(INCLUDES)
NVCCFLAGS := -Xcompiler "/W3" -g $(INCLUDES)

TARGET := bin/castlemania.exe

CPP_SOURCES := $(shell powershell -NoProfile -Command "Get-ChildItem src -Recurse -Filter *.cpp | %% { $$_.FullName }")
CU_SOURCES := $(shell powershell -NoProfile -Command "Get-ChildItem src -Recurse -Filter *.cu | %% { $$_.FullName }")

CPP_OBJECTS := $(CPP_SOURCES:.cpp=.obj)
CU_OBJECTS := $(CU_SOURCES:.cu=.obj)

OBJECTS := $(CPP_OBJECTS) $(CU_OBJECTS)

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(NVCC) $(OBJECTS) -o $@ 

%.obj: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

%.obj: %.cu
	$(NVCC) $(NVCCFLAGS) -c $< -o $@

clean:
	del /S /Q *.obj 2>nul
	del /Q $(TARGET) 2>nul

.PHONY: all clean